//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiauMvcApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiauShopDBEntities : DbContext
    {
        public KiauShopDBEntities()
            : base("name=KiauShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AboutTb> AboutTb { get; set; }
        public DbSet<NewsTb> NewsTb { get; set; }
        public DbSet<ProductGroupTb> ProductGroupTb { get; set; }
        public DbSet<UserTb> UserTb { get; set; }
        public DbSet<SlideShowTb> SlideShowTb { get; set; }
        public DbSet<ContactUsTb> ContactUsTb { get; set; }
        public DbSet<NewslettersTb> NewslettersTb { get; set; }
        public DbSet<ProductTb> ProductTb { get; set; }
    }
}
