//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiauMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsTb
    {
        public int NewsId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDescription { get; set; }
        public string NewsContent { get; set; }
        public string NewsPhotoUrl { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
    }
}
