//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiauMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTb
    {
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public string UserPassword { get; set; }
    }
}
