//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiauMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsTb
    {
        public int CuId { get; set; }
        public string CuFullName { get; set; }
        public string CuEmail { get; set; }
        public string CuCelephone { get; set; }
        public string CuContent { get; set; }
    }
}
