//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiauMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTb
    {
        public int ProductId { get; set; }
        public Nullable<int> ProductGroupIdFK { get; set; }
        public string ProductTitle { get; set; }
        public string ProductContent { get; set; }
        public string ProductPhotoUrl { get; set; }
        public string ProductPrice { get; set; }
        public string ProfessorName { get; set; }
        public string StudentName { get; set; }
        public string ProductFile { get; set; }
        public string ProductFreeFile { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
        public Nullable<bool> ProductIsSpeciall { get; set; }
    }
}
