//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiauMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideShowTb
    {
        public int SlideShowId { get; set; }
        public string SlideShowTitle { get; set; }
        public string SlideShowPhotoUrl { get; set; }
    }
}
